version: '3'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      # - 3306:3306
      - 3310:3310
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    networks:
      - mynetwork
    logging:
      driver: none

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - mynetwork
    logging:
      driver: none

volumes:
  mysql-data:

networks:
  mynetwork:
    driver: bridge
