import '@/app/globals.css'
import type { Metadata } from 'next'
import Provider from '../../context/provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <Provider>
        <body className="bg-background">{children}</body>
      </Provider>
    </html>
  )
}
